apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: whoami-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /

    nginx.ingress.kubernetes.io/proxy-connect-timeout: "10s"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "10s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "10s"

    nginx.ingress.kubernetes.io/load-balance: "round_robin"
spec:
  ingressClassName: nginx
  rules:
  - host: st-ab1-fadeev.ingress.sre-ab.ru
    http:
      paths:
      - pathType: Prefix
        path: "/whoami"
        backend:
          service:
            name: whoami-app-service
            port: 
              number: 80
