apiVersion: v1
kind: Secret
metadata:
  name: sage-credentials
type: Opaque
stringData:
  token: "eyJraWQiOiI2REFFREQ5Q0M5RUIxMDcyQUVDQTE4Qzg1RjMwNERFRDdGMEEyNDkxRERDRTYyNDk5RjlDRTkzRjlEOEJEODI1IiwidHlwIjoiSldUIiwiYWxnIjoiUlMyNTYifQ.eyJpc3MiOiJtYW51bCIsImV4cCI6NDEwMjQ0NDgwMCwiaWF0IjoxNzYyOTY1NzgzLCJncm91cCI6WyJzYWdlX2FiMV9mYWRlZXYiXSwidXBuIjoiYWIxX2ZhZGVldkBrZXljbG9hay5sb2NhbGhvc3QiLCJwZXJtaXNzaW9ucyI6W10sImNsaWVudElkIjoib25jYWxsX2luZGljYXRvcnMiLCJqdGkiOiI2MWE3M2UxNC0zN2NjLTQ0NTgtYjhmNC05Y2U1NzY5ODA1OTIifQ.2H1xislU-jDsLlPCynoEk2mavz_bSPrEznYHxaUpXZJGA5bYGQBn5y20Rh3JsR7Bpsl_Gyw5H82ckIoRRPdH3iFwP5UKs856EKBaZSpVOa46BV8Qj1NJxMm93HLJXUCD-FlFgi92IDoqON2MJLb1LDcB9SycSh4G4WS8MbEzP1kwbBFIw5VPPy0Fr2yaIF1dNbUcbzRC5RO2FNmRNDRx4d7PwOz_eAR-jpjFkQMgOswyDKBpFAJ3CvQ_TytbuEEvYMSX38hSh81m3gnBtqxjf9aD423R0aj9ATAIoMnuShdCaZnz6mP1ypkPkyVOaQWi-l_eb2RbzWuBTP_7GnvRSA"
