apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-scripts
data:
  init-exporter-user.sql: |
    CREATE USER IF NOT EXISTS 'exporter'@'%' IDENTIFIED BY 'password' WITH MAX_USER_CONNECTIONS 3;
    GRANT PROCESS, REPLICATION CLIENT, SELECT ON *.* TO 'exporter'@'%';
    FLUSH PRIVILEGES;