apiVersion: v1
kind: Service
metadata:
  name: oncall-prober
  labels:
    app.kubernetes.io/name: oncall-prober
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9110"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: oncall-prober
  ports:
    - protocol: TCP
      port: 9110
      targetPort: 9110
  type: ClusterIP
