apiVersion: v1
kind: Service
metadata:
  name: deployment-strategies-service
  labels:
    app: my-app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9101"
    prometheus.io/path: "/metrics"
spec:
  selector:
    app: my-app
    version: "v1.0.0"
  ports:
  - name: app
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 9101
    targetPort: 9101
